### ISSUE TITLE
Show timestamps in local timezone, not UTC

### ISSUE THREAD

**Issue by daybreaker** [codefornola/nola-transit-map#2]
Timestamps are currently a UTC string. For usability purposes, they should be presented in a format displayed in the local time zone.

Also, I noticed the timestamp doesnt seem to include seconds? They are always ":00"  If seconds dont need to be displayed, consider removing them in the formatted timestamp.

**Comment by bhelx** [comment]
Thanks! Good recommendations.

> Timestamps are currently a UTC string. For usability purposes, they should be presented in a format displayed in the local time zone.

I think I saw this comment on reddit, It's the local timezone, not UTC, but it's an ISO string (which uses 24-hour format) so yeah not very friendly. I'd like to redesign the popup in general, but for the timestamp maybe change it to a colloquial "time ago" format. For example: `13s ago` or `3m23s ago`. Depends on the precision we can get. A UX person just started helping out so maybe he will have some ideas on how to communicate the staleness of the data.

> Also, I noticed the timestamp doesnt seem to include seconds? They are always ":00" If seconds dont need to be displayed, consider removing them in the formatted timestamp.

I'll see if there is another timestamp field. I think this is the best precision we have. But to your point, yeah maybe we just ignore the seconds part.

**Comment by bhelx** [comment]
Closed with https://github.com/codefornola/nola-transit-map/pull/4
