### ISSUE TITLE
Bus location not working and route 55 update 

### ISSUE THREAD

**Issue by Motnug** [codefornola/nola-transit-map#21]
Cannot load routes or see bus locations.
Also the bus 55 route is different than shown on the east side of the route by the Gentilly wallyworld.

**Comment by bhelx** [comment]
The app gets data from an API at `bustime.norta.com` which seems to have disappeared. It's possible they moved it or it's down temporarily. The DNS records are still there so the latter is more likely:

```
dig bustime.norta.com

; <<>> DiG 9.10.6 <<>> bustime.norta.com

;bustime.norta.com.		IN	A

;; ANSWER SECTION:
bustime.norta.com.	1277	IN	A	142.190.113.10

```

**Comment by bhelx** [comment]
Can you explain what you mean by the second part?

> Also the bus 55 route is different than shown on the east side of the route by the Gentilly wallyworld.

**Comment by Motnug** [comment]
The bus down to the Gentilly walmart goes on the other side of the golf
course on Congress, on the way back it takes Press drive up to LC Simon.

**Comment by bhelx** [comment]
Seems they brought it back online and should be working now.

> The bus down to the Gentilly walmart goes on the other side of the golf
course on Congress, on the way back it takes Press drive up to LC Simon.

I see, yes the routes themselves are out of date. We don't have a process to keep them up to date. I have an issue open here if someone wants to work on it: https://github.com/codefornola/nola-transit-map/issues/23

**Comment by Motnug** [comment]
Great news on it being up, appreciate you getting back and checking. I
would offer to help update the routes if I had any coding experience. The
website has been a life saver these past few months. Thanks to you and all
who help!
