### ISSUE TITLE
No vehicles  found

### ISSUE THREAD

**Issue by leknola** [codefornola/nola-transit-map#8]
Having trouble getting the website to open, once open no luck finding vehicles. Please help! The 91 notoriously runs behind schedule, if I can see how many buses are on the line it's extremely helpful for me to get to work. What y'all have created is an incredible asset for me and all New Orleanians who take public transportation! 
Thank you!!

**Comment by artiemcaddikins** [comment]
Same! 91 rider here, too. This is an amazing page & I don’t ever want to see it go!

**Comment by bhelx** [comment]
Thanks for letting us know. I've been at a conference this week so only just now seeing this.

The app was hard down, i rebooted it. It came back up. But I'm getting 0 vehicles back from the RTA. Also their API is intermittently crashing.

I've sent a note to the one person I know there. Will see what they say. It could be that they finally cut me off. I'm not entirely sure if I am supposed to have access to this API or not or if they are cool with it.

**Comment by artiemcaddikins** [comment]
Wow, thank you! On Apr 20, 2023, at 4:16 PM, Benjamin Eckel ***@***.***> wrote:﻿
Thanks for letting us know. I've been at a conference this week so only just now seeing this.
The app was hard down, i rebooted it. It came back up. But I'm getting 0 vehicles back from the RTA. Also their API is intermittently crashing.
I've sent a note to the one person I know there. Will see what they say. It could be that they finally cut me off. I'm not entirely sure if I am supposed to have access to this API or not or if they are cool with it.

**Comment by artiemcaddikins** [comment]
Also, that site of yours was the BEST. Regardless of the outcome, you are amazing for creating that for everyone 🥰On Apr 20, 2023, at 4:16 PM, Benjamin Eckel ***@***.***> wrote:﻿
Thanks for letting us know. I've been at a conference this week so only just now seeing this.
The app was hard down, i rebooted it. It came back up. But I'm getting 0 vehicles back from the RTA. Also their API is intermittently crashing.
I've sent a note to the one person I know there. Will see what they say. It could be that they finally cut me off. I'm not entirely sure if I am supposed to have access to this API or not or if they are cool with it.

**Comment by bhelx** [comment]
Thanks for the encouragement. A few people  in the codefornola community put this together so I can’t really take all the credit.

I’ll try to work with the RTA to get an official word on this API moving forward though. I’ve been kind of afraid to ask them if I’m actually allowed to be using it.

**Comment by leknola** [comment]
Y'all's site is the best! If RTA has any concern for riders they should
welcome it. I've shown it to everyone I meet at bus stops and on the bus.
It's been a lifesaver for me getting to work on time! LePass is an abysmal
app. Thank y'all!

**Comment by artiemcaddikins** [comment]
SAME!!!! People are always so thankful! Even after NORTA added the “live” feature, it doesn’t work! I hope to goodness it works out. If there’s anything I can do to help, any letters or anything to be written, ANYTHING, please holler!-Angela Timberlake Adkinson504-874-5956On Apr 20, 2023, at 4:58 PM, leknola ***@***.***> wrote:﻿
Y'all's site is the best! If RTA has any concern for riders they should
welcome it. I've shown it to everyone I meet at bus stops and on the bus.
It's been a lifesaver for me getting to work on time! LePass is an abysmal
app. Thank y'all!

**Comment by leknola** [comment]
Ditto Angela!
Please reach out if I can help in any way!
Laura E Kajioka 504-762-0377

**Comment by bhelx** [comment]
Yes, now might be time to take community action. I thought this app would be a holdover until they got it working in LePass. It's embarrassing. If someone could update this reddit thread and let them know what i going on that would be appreciative. I don't have an active reddit account

https://www.reddit.com/r/NewOrleans/comments/12sx18u/the_best_rta_tracker_looks_to_be_out_of_commission/

**Comment by artiemcaddikins** [comment]
Sure thing! I have one, “SwampyBiscuits” is my name…which is too awesome not to share. On Apr 20, 2023, at 7:25 PM, Benjamin Eckel ***@***.***> wrote:﻿
Yes, now might be time to take community action. I thought this app would be a holdover until they got it working in LePass. It's embarrassing. If someone could update this reddit thread and let them know what i going on that would be appreciative. I don't have an active reddit account
https://www.reddit.com/r/NewOrleans/comments/12sx18u/the_best_rta_tracker_looks_to_be_out_of_commission/

**Comment by plumwski** [comment]
I'd just like to pop in as well and stay thanks to everyone who developed this app.  It's a great demonstration of how the official RTA needs to operate in terms of tracking busses.  Always-on, both ways on the route.   Just great.  Thanks for everything and I hope the RTA gets it's API working again soon.

**Comment by estancioff** [comment]
Heyyy I work at RTA and can check with our IT team today to see if someone deactivated the API key or what else might have happened. One question - did y'all pull down the whole App for now? I can't access even the map at the moment. 
Also yes thank you for developing this. While I understand that the apps that are out there (Moovit and Transit) might be a decent generic solution for using transit in other cities or when traveling, local transit riders in New Orleans have different needs - we need to be able to see all available information about vehicle locations (and whether they exist at all) in its rawest form, which is what this app does really well.

**Comment by bhelx** [comment]
@estancioff thanks! let me know if there is anything you need from me. the API i'm accessing is the same API that GoMobile was using (by clever devices). I'm not sure which one LePass is using. But since LePass didn't work but GoMobile did, I figured I could make something emulating GoMobile until LePass worked.

**Comment by bhelx** [comment]
@estancioff Another thing. We'd be happy to donate this to the RTA and make some improvements to it. There is a pretty big community of coders here who could easily professionalize and even help maintain this if we had a little support on the RTA side.

I fought pretty hard to get real-time access and even helped on the RFP that clever devices won / implemented. For a little while, when GoMobile was released, transit was actually usable in the city for me again. LePass felt like such a soul crushing step backwards for me. That's why I was willing to put some weekends in to make this, just for myself. Because I couldn't even get around the city. And it seems to have struck a chord with a lot of other folks. I understand you're probably not in a position to do a lot about this feedback but if you can point someone to this thread, and the numerous Reddit threads about this, that might help with the sense of urgency. Really we're all here to help.

**Comment by bhelx** [comment]
@estancioff Thanks so much for the detailed response! Really appreciate it. If you can get an email chain or a meeting going let me know. Happy to explain more to IT. My email is bhelx@simst.im

> OK. I've been told that our policy is that you have to fill out the form that can be found here under the "Real Time Data Feed" section, to get a developer key: https://www.norta.com/help-and-contacts/business-information/open-transit-data-(otd)

Yeah, I've done this a few dozen times over the last decade. I'd do it again, but I noticed the only option they show is `Decline` on this page:

<img width="1255" alt="Screenshot 2023-04-21 at 4 11 23 PM" src="https://user-images.githubusercontent.com/185919/233735436-c3236fc6-762c-4442-94ce-ab07dcc7baf7.png">

Scrolling to the bottom does not bring back the `agree` button. I stopped being able to get past this page a few months ago.

> They deactivated a bunch of these recently that they didn't think anyone should be using (they emailed the contact for the key but obviously it wasn't your email on there.) The policy is to have a unique key for each individual using the realtime data.

I don't think this public one is the API I am using. To my knowledge, they never released actual access to the clever devices API. I believe that one was still the old API from the BusGuard days. At least, that is what they tried to send me every time i requested access. 

What I am accessing here on this project is / was the clever devices, bustime system But it appears the IP is no longer responding: http://72.158.203.4/

I suppose it's possible they changed the IP address. I never got a DNS record to point to for it. @estancioff could you check that? maybe there is a new IP address I can use. Ideally this would be behind a domain name I can point to so changing IP addresses won't affect clients which is standard practice for APIs and websites.

> There are two different API's that we can provide - you were using the bustime API (this is CleverDevice's unique format), and the other is the GTFS-RT, which is the standardized/open source format and they might try to push on you. I think you'll have to specify you want bustime otherwise i think you'll have to modify your code.

Ideally I could use GTFS-RT. I was the one who actually made sure that was put in the RFP, but I could never get a straight answer whether it was implemented or not. Right now we use the bustime format, but I don't mind modifying the code assuming it's a fully featured implementation. How do I get access to that?

> They also will probably lower your refresh rate, because they're worried about our bandwidth or whatever. Maybe all this can be the start of the conversation about partnering with RTA for this app though. IT may not be able to help with that part for now, but if you get this back up and running and we can show that people are using it, I can set up a conversation for you with someone else who could maybe make something happen.

We cache all the positions on our server. So we only hit the API once every 5 seconds or so regardless of how many users are using the app. I designed it that way so there would be basically 0 impact on bandwidth.

**Comment by estancioff** [comment]
Hey @bhelx Thanks for answering my email. I sent you an invite for 2 PM on Wednesday. Hope we can get all these questions answered and get you all the access you need.

**Comment by bhelx** [comment]
Hey everyone. @estancioff was able to get us a meeting with RTA and we were able to resolve the issue. We still need to migrate to a new api key but should happen without interruption in the next few days.

**Comment by artiemcaddikins** [comment]
WOOHOOOOO!!!! That’s great!Thank you so much 😊 On May 3, 2023, at 6:13 PM, Benjamin Eckel ***@***.***> wrote:﻿
Hey everyone. @estancioff was able to get us a meeting with RTA and we were able to resolve the issue. We still need to migrate to a new api key but should happen without interruption in the next few days.

**Comment by artiemcaddikins** [comment]
I cheered!!! I actually cheered when I saw this 😆😆😆Thanks, yet again!!!-AngelaOn May 4, 2023, at 2:03 AM, Angela Timberlake ***@***.***> wrote:﻿WOOHOOOOO!!!! That’s great!Thank you so much 😊 On May 3, 2023, at 6:13 PM, Benjamin Eckel ***@***.***> wrote:﻿
Hey everyone. @estancioff was able to get us a meeting with RTA and we were able to resolve the issue. We still need to migrate to a new api key but should happen without interruption in the next few days.

**Comment by leknola** [comment]
I can't thank y'all enough for your diligence in getting this resolved! Forever grateful.

**Comment by plumwski** [comment]
Agreed, this is fantastic news!
